variables:
  DOCKER_IMAGE: pipeline-operations-centre

stages:
- test
- build
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- project: 'LibertyAces/Product/bitswanmonorepo'
  file: 'cicd/docker-build-public.yml'
