
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

variables:
  DOCKER_IMAGE: pipeline-operations-centre

include:
  - project: 'LibertyAces/Product/bitswanmonorepo'
    file: 'cicd/docker-build-public.yml'
