name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Get Year and Commit Hash
      id: vars
      run: |
        echo "::set-output name=year::$(date +%Y)"
        echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Get JOB ID
      uses: qoomon/actions--context@v1
      id: context

    - name: Build and Push
      env:
        BUILD_NO: ${{ steps.context.outputs.job_id }}
      run: bash build_and_push.sh